sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
  - osx
      
install:
  - yarn

script:
  - yarn travix node
  # - yarn travix cs # type paramters...
  # - yarn travix java # type paramters...
  # - yarn travix python # ???
  - yarn travix php
  - yarn travix cpp
  # - yarn travix lua 
  - yarn travix neko
  - yarn travix interp
